tests: fix cache issue causing random failure in testAuthenticationPolicy
Traceback (most recent call last):
  File "Products/ERP5/tests/testAuthenticationPolicy.py", line 538, in test_05_HttpRequest
    self.assertFalse(person.isLoginBlocked())
  File "Products/ERP5/mixin/login_account_provider.py", line 68, in isLoginBlocked
    return method(**kw)
  File "ZODB/Connection.py", line 857, in setstate
    raise ConnectionStateError(msg)
ConnectionStateError: Shouldn't load state for 0x6c90 when the connection is closed